FROM ubuntu:20.04

ENV TZ Asia/Seoul
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get install -y curl \
    && apt-get install -y openjdk-8-jdk

RUN apt-get clean autoclean && \
    apt-get autoremove --yes && \
    rm -rf /var/lib/apt/lists/*

# Hadoop 구성
ENV HADDOP_VERSION=3.2.4
ENV HADOOP_URL=https://dlcdn.apache.org/hadoop/common/hadoop-$HADDOP_VERSION/hadoop-$HADDOP_VERSION.tar.gz

RUN curl -fSL "${HADOOP_URL}" -o /tmp/hadoop.tar.gz \
    && tar -zxvf /tmp/hadoop.tar.gz -C /opt/ \
    && rm /tmp/hadoop.tar.gz

RUN ln -s /opt/hadoop-${HADDOP_VERSION} /opt/hadoop \
    && mkdir /opt/hadoop/dfs \
    && ln -s /opt/hadoop-${HADDOP_VERSION}/etc/hadoop /etc/hadoop \
    && rm -rf /opt/hadoop/share/doc

COPY core-site.xml /etc/hadoop

ENV HADOOP_PREFIX /opt/hadoop
ENV HADOOP_CONF_DIR /etc/hadoop
ENV PATH ${HADOOP_PREFIX}/bin:$PATH
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-arm64